import sys

with open(r'C:\Users\patri\OneDrive\BaSIM\src\main_phase3_step32_time_varying.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = []
for line in lines:
    if 'f.write' in line and '\\n' not in line and '")' not in line:
        # It's likely a broken newline
        pass
    new_lines.append(line)

# Let's just rewrite the exact MVR block cleanly!
import re
with open(r'C:\Users\patri\OneDrive\BaSIM\src\main_phase3_step32_time_varying.py', 'r', encoding='utf-8') as f:
    content = f.read()

mvr_pattern = r'def create_mvr_package.*?return mvr_file'
new_mvr = '''def create_mvr_package(
    basin_cells,
    stress_periods,
    model_dir,
    model_name,
    delr,
    delc,
    lak_pname="basin_lak",
    uzf_pname="basin_uzf",
):
    import os
    print(f"   ?? Creating MVR package ({len(basin_cells)}x2 movers)...")

    mvr_file = os.path.join(model_dir, f"{model_name}.mvr")
    nmovers = len(basin_cells) * 2

    # Compute area fractions
    def _cell_area(row, col):
        dx = float(delr[col]) if hasattr(delr, '__len__') else float(delr)
        dy = float(delc[row]) if hasattr(delc, '__len__') else float(delc)
        return dx * dy

    areas = [_cell_area(r, c) for (_, r, c) in basin_cells]
    total_area = sum(areas)
    fractions = [a / total_area for a in areas]

    with open(mvr_file, 'w') as f:
        f.write("# MVR Package - Water Mover: LAK seepage -> UZF -> LAK\\n")
        f.write("# Generated by BaSIM\\n\\n")

        f.write("BEGIN OPTIONS\\n")
        f.write("  PRINT_FLOWS\\n")
        f.write("END OPTIONS\\n\\n")

        f.write("BEGIN DIMENSIONS\\n")
        f.write(f"  MAXMVR {nmovers}\\n")
        f.write("  MAXPACKAGES 2\\n")
        f.write("END DIMENSIONS\\n\\n")

        f.write("BEGIN PACKAGES\\n")
        f.write(f"  {lak_pname}\\n")
        f.write(f"  {uzf_pname}\\n")
        f.write("END PACKAGES\\n\\n")

        # Same mover entries every stress period
        for sp_idx in range(len(stress_periods)):
            sp_num = sp_idx + 1
            f.write(f"BEGIN PERIOD {sp_num}\\n")
            f.write(f"# pname1 id1 pname2 id2 mvrtype value\\n")
            
            # Forward: LAK -> UZF
            for idx in range(len(basin_cells)):
                uzf_id = idx + 1
                f.write(f"  {lak_pname}  1  {uzf_pname}  {uzf_id}  FACTOR  {fractions[idx]:.8f}\\n")
                
            # Return: UZF (REJINF) -> LAK
            for idx in range(len(basin_cells)):
                uzf_id = idx + 1
                f.write(f"  {uzf_pname}  {uzf_id}  {lak_pname}  1  FACTOR  1.00000000\\n")
                
            f.write(f"END PERIOD\\n\\n")

    print(f"   ? MVR file created: {os.path.basename(mvr_file)}")
    return mvr_file'''

content = re.sub(mvr_pattern, new_mvr, content, flags=re.DOTALL)
with open(r'C:\Users\patri\OneDrive\BaSIM\src\main_phase3_step32_time_varying.py', 'w', encoding='utf-8') as f:
    f.write(content)
print('Fixed!')
