<template>
  <div class="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-4xl mx-auto bg-white rounded-lg shadow px-8 py-10 text-gray-800">
      
      <div class="flex items-center justify-between border-b pb-6 mb-6">
        <div>
          <h1 class="text-3xl font-bold text-gray-900">Software-as-a-Service (SaaS) Terms of Service</h1>
          <p class="mt-2 text-sm text-gray-500">Effective from 18 June 2026</p>
        </div>
        <button @click="$router.go(-1)" class="text-sm font-medium text-blue-600 hover:text-blue-500">
          &larr; Go Back
        </button>
      </div>

      <div class="prose prose-sm max-w-none prose-blue">
        <p>
          These Terms of Service (“Terms”) are a legal agreement between you (“Licensee”) and 
          <strong>Patrick John Hayes trading as Innealta (ABN 40 712 622 037)</strong> (“Licensor”), 
          the author of the BaSIM software and its associated web platform (“Software”).
        </p>
        <p>
          If you are agreeing to these Terms not as an individual but on behalf of a company, government body, organisation or other legal entity (“Entity”), then Licensee means the Entity, and you are binding the Entity to these Terms and you agree that you have the authority to do so.
        </p>
        <p>
          By creating an account, purchasing credits, or otherwise accessing the Software, the Licensee agrees to be bound by the terms and conditions set forth in these Terms. If the Licensee does not agree to these terms, the Licensee may not access or use the Software.
        </p>

        <h3>1. Definitions</h3>
        <ul>
          <li><strong>“Licensor”</strong> refers to Patrick John Hayes trading as Innealta, ABN 40 712 622 037, Western Australia 6050, Australia.</li>
          <li><strong>“Licensee”</strong> means you, the individual or Entity that creates an account, purchases credits, or uses the Software.</li>
          <li><strong>“Software”</strong> means the BaSIM web application, API, simulation engine, and associated online documentation provided as a Software-as-a-Service (SaaS).</li>
          <li><strong>“Credits”</strong> means prepaid digital tokens purchased by the Licensee, which are consumed upon running simulations within the Software.</li>
        </ul>

        <h3>2. Right to Access and Use</h3>
        <p>
          Subject to these Terms and the payment of applicable fees (Credits), the Licensor hereby grants to the Licensee a non-exclusive, non-transferable, revocable right to access and use the SaaS via a web browser for the Licensee's internal business purposes.
        </p>

        <h3>3. Rights and Limitations</h3>
        <ul>
          <li><strong>No Resale or Sub-licensing:</strong> The Licensee is not allowed to distribute, sublicense, rent, or lease access to the Software or any part thereof to any third party.</li>
          <li><strong>No Reverse Engineering:</strong> The Licensee must not reverse engineer, decompile, or disassemble the Software, its API, or its underlying simulation models.</li>
          <li><strong>Account Security:</strong> The Licensee is responsible for maintaining the confidentiality of their login credentials. Each set of login credentials must be tied to one individual human being and may not be shared.</li>
        </ul>

        <h3>4. Intellectual Property</h3>
        <p>
          All rights, title, interest, and copyrights in and to the Software and any part thereof, including but not limited to all algorithms, simulation models, databases, interface designs, and text, are owned by the Licensor. The Software is protected by applicable copyright laws and international treaties. The Licensee retains full ownership of the specific input data they provide to the Software and the specific simulation output data/reports generated by their account.
        </p>
        <p>
          The Licensee grants the Licensor a non-exclusive, worldwide, royalty-free license to host, process, and use the input data solely for the purpose of operating the Software, performing simulations, and generating outputs for the Licensee. The Licensor may also use anonymized and aggregated basin data to train, improve, or enhance the Software's simulation engine.
        </p>

        <h3>5. Payment and Credits</h3>
        <p>
          Access to simulation functionality within the Software requires the consumption of Credits. Except as required by the Australian Consumer Law, Credits are purchased prepaid and are strictly non-refundable. Credits hold no cash value and cannot be exchanged for fiat currency. The Licensor reserves the right to modify the cost of Credits or the amount of Credits required for specific simulations at any time, which will apply to future usage.
        </p>

        <h3>6. Warranty Disclaimer</h3>
        <p>
          The Licensor provides the Software “as is” without warranty of any kind, either expressed or implied, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, error-free operation, or accuracy of simulation results. 
        </p>
        <p>
          <strong>Engineering and Financial Disclaimer:</strong> The Software provides simulated mathematical estimations based on the input data provided by the Licensee. The Licensor does not guarantee that the simulation results will perfectly reflect real-world hydrological events, flood levels, catchment behaviors, or drainage outcomes. The Licensee assumes all risk for any civil engineering, design, or commercial decisions made based on the output of the Software.
        </p>

        <h3>7. Limited Liability</h3>
        <p>
          To the extent permitted by law, if a statutory guarantee under the Australian Consumer Law is breached, the Licensor's liability is limited to either the resupply of the services or the cost of having the services resupplied.
        </p>
        <p>
          Otherwise, under no circumstances shall the Licensor be liable to the Licensee, or any other person or entity claiming through the Licensee, for any loss of profits, income, savings, or any other consequential, incidental, special, punitive, direct, or indirect damage, whether arising in contract, tort, warranty, or otherwise, even if the Licensor has been advised of the possibility of such damages. The Licensor’s aggregate liability to the Licensee shall not exceed the total monetary amount actually paid by the Licensee to the Licensor for the purchase of Credits in the twelve (12) months preceding the claim.
        </p>

        <h3>8. Termination</h3>
        <p>
          These Terms are effective until terminated by either party. The Licensee may terminate this agreement at any time by ceasing all use of the Software. The Licensor may terminate these Terms and suspend or delete the Licensee's account immediately upon written notice if the Licensee breaches any of the terms and conditions set forth herein. Upon termination, all rights granted to the Licensee will immediately cease, and unused Credits will be forfeited without refund.
        </p>

        <h3>9. Jurisdiction</h3>
        <p>
          These Terms shall be deemed to have been made in, and shall be construed pursuant to the laws of Western Australia, Australia, without regard to conflicts of the law’s provisions thereof. Any legal action or proceeding relating to these Terms shall be brought exclusively in the courts located in Western Australia, and each party consents to the jurisdiction thereof.
        </p>

        <h3>10. Severability</h3>
        <p>
          If any provision of these Terms shall be adjudged by any court of competent jurisdiction to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect and enforceable.
        </p>

        <h3>11. Entire Agreement</h3>
        <p>
          This Agreement constitutes the entire agreement between the Licensor and the Licensee regarding the use of the Software and supersedes all prior understandings of the Licensor and the Licensee, including any prior representation, statement, condition, or warranty.
        </p>
      </div>

    </div>
  </div>
</template>

<script setup lang="ts">
// Static Terms of Service page, no logic required
</script>
